//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResearcherInfoService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResearcherApproval
    {
        public int ProjectId { get; set; }
        public int ResearcherAvailabilityId { get; set; }
        public int ApprovalStatusId { get; set; }
        public string InfoRequested { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public int ResearcherId { get; set; }
    
        public virtual ApprovalStatus ApprovalStatus { get; set; }
        public virtual Project Project { get; set; }
        public virtual ResearcherAvailability ResearcherAvailability { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
